name: Add issue to project

on:
  workflow_call:
    inputs:
      project_id:
        type: number
        description: The ID of the project to add the issue to
        default: 2
jobs:
  add-issue-to-project:
    name: Add issue with `status/triage` label to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@f04aa94d10cf56334d1c580e077ce2e3569e805d # v1.6.3
        with:
          app_id: ${{ vars.JANUS_IDP_GITHUB_APP_ID }}
          private_key: ${{ secrets.JANUS_IDP_GITHUB_APP_PRIVATE_KEY }}
      - name: Add issue to project
        run: gh project item-add ${{ inputs.project_id }} --owner ${{ github.event.organization.login }} --url ${{ github.event.issue.html_url }}
        env:
          # token needs to have read/write permissions for projects on org level
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
